### ISSUE TITLE
Issue about the ConsistentModalitySampler

### ISSUE THREAD

**Issue by workingcoder** [dyhBUPT/BUPTCampus#3]
Firstly, thank you for your work in providing a new dataset and baseline method for Video VI ReID task !
Here, I am a bit confused about the reason for introducing the ConsistentModalitySampler, as it will discard some test samples.
Can you explain the reason?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

It is actually a legacy issue. While testing, we need to ensure that samples in one batch are from the same modality (RGB or IR). And we want to use only one dataset to perform testing, not two for these two modalities respectively. Therefore, we introduce this sampler, which will drop a few samples.

This has little impact on performance evaluation. And you can also try to fix this issue~

Best wishes.
