### ISSUE TITLE
The meaning of the path of img_files?

### ISSUE THREAD

**Issue by 924973292** [dyhBUPT/BUPTCampus#4]
<img width="240" alt="截屏2024-01-05 17 52 57" src="https://github.com/dyhBUPT/BUPTCampus/assets/89966785/565c6a87-5a7f-4875-b2c5-8bf2d196c9c7">
Thanks for your work!
I am new to this area, and I am wondering what's the meaning of each part of the path?
2949 means the ID、RGB means the modality、W4 means the camera type, what about the 1?
It means the video series?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

Under one camera, one person may have multiple tracklets (caused by occlusion, etc.).
And the `1` here is the tracklet id, and `12415` is the frame id.

Best wishes.

**Comment by 924973292** [comment]
Thanks！
