### ISSUE TITLE
How to test on the HITSZ-VCM dataset?

### ISSUE THREAD

**Issue by xiaoye-hhh** [dyhBUPT/BUPTCampus#5]
How to test this method on the HITSZ-VCM dataset?

**Comment by dyhBUPT** [comment]
Hi, you should rewrite the dataloader to load VCM-HITSZ in an appropriate manner.

**Comment by xiaoye-hhh** [comment]
Can more indicators be provided (R-5, R-10, R-20 in HITSZ-VCM)?

**Comment by dyhBUPT** [comment]
Sure~ 
The `mAP / R-1 / R-5 / R-10 / R-20` for mode `R2I` and `I2R` are:
- Baseline：`36.90 / 52.34 / 67.56 / 74.52 / 80.13` and `36.26 / 49.32 / 65.12 / 71.55 / 77.29`
- +re-ranking：`48.70 / 54.58 / 67.15 / 74.66 / 81.11` and `45.99 / 51.05 / 63.44 / 70.42 / 77.92`

**Comment by xiaoye-hhh** [comment]
Thank you!
